function runMRTTask(options)
    % RUNMRTTASK Runs a sample MATLAB Runtime Task on Databricks

    arguments (Input)
        options.cluster {databricks.internal.cluster.mustBeScalarClusterOrId}
        options.dockerAuthFile string {mustBeFile}
    end

    if isfield(options, 'cluster')
        cluster = options.cluster;
        if isa(cluster, 'databricks.Cluster')
            cluster = cluster.cluster_id;
        end
        jobNamePrefix = "MATLABRuntimeTaskExample-RunOnExistingCluster";
    else
        if isfield(options, "dockerAuthFile")
            cluster = createDatabricksCluster("MATLABRuntimeTaskTestCluster", 0, dockerAuthFile=options.dockerAuthFile);
            jobNamePrefix = "MATLABRuntimeTaskExample-RunOnNewCluster";
        else
            error("A dockerAuthFile file must be specified if not using an existing cluster, which may be init script based.")
        end
    end

    results = buildBinary();
    [~, fname, fext] = fileparts(string(results.Files{1}));
    binaryName = fname + fext; % In Linux there will be no ext but allow it for testing
    ws = databricks.Workspace();
    assert(endsWith(results.Files{1}, binaryName));
    srcFile = results.Files{1};
    dstFile = "/Workspace/Users/" + string(ws.username) + "/tmp/" + string(binaryName);
    ws.import('path', dstFile, ...
            'format', 'RAW', ...
            'file', srcFile, 'overwrite', true);

    % This notebook will be generated by MATLABRuntimeTask
    notebookPath = "/Workspace/Users/" + string(ws.username) + "/tmp/" + string(binaryName) + "Notebook.py";

    t = databricks.MATLABRuntimeTask(dstFile,...
        arguments="3.14",...
        notebookPath=notebookPath,...
        preExecPyCmd='print("Running preExec Python")',...
        postExecPyCmd='print("Running postExec Python")',...
        preExecShCmd='echo "Running preExec Shell"',...
        postExecShCmd='echo "Running postExec Shell"');

    job = databricks.Job;
    job.name = jobNamePrefix;

    % Assign the cluster to the job
    job.setCluster(cluster);

    job.setTask(t);
    job.create();
    jobRun = job.runNow();

    fprintf("Expected output is: 3.14\n");
    fprintf('Created job "%s", see run <a href="%s">here</a>\n', job.name, jobRun.run_page_url);

    % Delete the temporary notebook
    % ws.delete(notebookPath);
end
