function payload = getPayload(obj, varargin)
    % GETPAYLOAD Internal method to create the request payload by removing properties

    %  Copyright 2021-2022 MathWorks, Inc.

    % Create a candidate payload
    % name - STRING - Register model under this name This field is required.
    % source - STRING - URI indicating the location of the model artifacts.
    %        This field is required. 
    % run_id - STRING - MLflow run ID for correlation, if source was
    %        generated by an experiment run in MLflow tracking server
    % tags - An array of ModelVersionTag - Additional metadata for model version.
    % run_link - STRING - MLflow run link - this is the exact link of the
    %        run that generated this model version, potentially hosted at
    %        another instance of MLflow. 
    % description - STRING - Optional description for model version.

    candidate.name = obj.name;
    candidate.source = obj.source;
    if ~isempty(obj.run_id)
        candidate.run_id = obj.run_id;
    end
    if ~isempty(obj.tags)
        candidate.tags = obj.tags;
    end
    if ~isempty(obj.run_link)
        candidate.run_link = obj.run_link;
    end
    if ~isempty(obj.description)
        candidate.description = obj.description;
    end

    payload = jsonencode(candidate);

end %function
