function jsonFileName = generateFunctionSignature(funcName, arg)
    % generateFunctionSignature Helper function to get function signature
    %
    % This function creates a JSON file that provides the SparkBuildercan
    % with additional information when compiling functions that should run
    % on Spark clusters.
    %
    % The function takes two or three arguments:
    %   funcName - The name of the function (without .m ending) this
    %              signature is for
    %   IN       - A cell array of arguments for the function
    %   OUT      - A cell array of return values for the function
    %
    % It will automatically create a JSON file in the same location as the
    % function, but with the ending "_signature.json" instead of ".m".
    % The function also returns the name of the JSON file, but this can
    % mostly be ignored.
    %
    % Examples:
    %  % Importing the function, to make examples shorter
    %  import compiler.build.spark.types.generateFunctionSignature
    %
    % A function that takes 3 scalar double values, and returns two
    % double scalars:
    %  generateFunctionSignature('simplecalc', {3, 4, 5}, {1, 2})
    %
    % The same signature can be generated by simply omitting the output
    % values. In this case, the function will simply call the actual
    % function with the input values provided, and use the results of this
    % as the OUT argument.
    %  generateFunctionSignature('simplecalc', {3, 4, 5})
    %
    % A function that takes a table and a scalar, and returns another table
    %  generateFunctionSignature('gaussianFilter', {T_in, 4})

    % Copyright 2022 The MathWorks, Inc.

    arguments
        funcName
    end
    arguments (Repeating)
        arg cell
    end

    narginchk(2, 3);

    assert(...
        isa(funcName, 'function_handle') || ...
        isStringScalar(funcName) || ...
        (ischar(funcName) && isrow(funcName)))


    FIS = compiler.build.spark.internal.getFcnFileName(funcName);

    jsonFileName = compiler.build.spark.internal.getJSONName(FIS.FullFileName);

    IN = arg{1};

    nIn = nargin(FIS.FuncHandle);
    nOut = nargout(FIS.FuncHandle);

    assert(...
        isa(funcName, 'function_handle') || ...
        isStringScalar(funcName) || ...
        (ischar(funcName) && isrow(funcName)))


    FIS = compiler.build.spark.internal.getFcnFileName(funcName);

    jsonFileName = compiler.build.spark.internal.getJSONName(FIS.FullFileName);

    nIn = nargin(FIS.FuncHandle);
    nOut = nargout(FIS.FuncHandle);

    IN = arg{1};
    % If no OUT argument was given, try generating this
    if nargin < 3
        try
            path_= FIS.FullPath;
            if ~isempty(path_) && strlength(path_) > 0
                if string(pwd) ~= path_
                    old = cd(path_);
                    goBack = onCleanup(@() cd(old));
                end
            end
            if nOut < 0
                error("SPARK_API:no_varargout_for_signatures", ...
                    "A function, for which a signature is generated, cannot have varargout as output");
            end
            OUT = cell(1,nOut);
            [OUT{1:nOut}] = FIS.FuncHandle(IN{:});
        catch EX
            error("SPARK_API:bad_function_name_signature", ...
                "The function name provided, %s, could not be evaluated properly.\n" + ...
                "Verify that the function can be called from the command line.", funcName);
        end
    else
        OUT = arg{2};
    end

    [inArgNames, outArgNames] = compiler.build.spark.internal.getArgNames(FIS.FullFileName);
    if isempty(inArgNames) && nIn > 0
        inArgNames = "in_" + (1:obj.nArgIn);
    end
    if isempty(outArgNames) && nOut > 0
        outArgNames = "out_" + (1:obj.nArgOut);
    end
    enc = compiler.build.spark.types.getTypeEncoding(IN, OUT, inArgNames, outArgNames);

    [fh, errmsg] = fopen(jsonFileName, "w");
    if fh < 0
        error("Could not open file '%s' for writing.\nMessage: %s\n", jsonFileName, errmsg);
    else
        whenDone = onCleanup(@() fclose(fh));
        fprintf(fh, '%s\n', enc);
    end

    if nargout == 0
        fprintf("Generated function signature:\n\t%s\n", jsonFileName);
        clear('jsonFileName');
    end
end

