function DI = DemoInfo()
    % DemoInfo Common info used for the demo

    % Copyright 2022-2026 The MathWorks, Inc.

    here = fileparts(mfilename('fullpath'));

    ws = databricks.Workspace;
    wsBase = "/Users/" + ws.username + "/";

    DI = struct(...
        "ProjectRoot", here, ...
        "FuncName", "predOutcomes", ...
        "FuncFileName", "predOutcomes.m", ...
        ...
        "BuildDir", fullfile(here, '_build'), ...
        "PythonPkgName", "example.trainedclassifier", ...
        ...
        "VolumesUploadFolder", '/Volumes/main/default/myvolume/Examples/MachineLearning', ...
        "PythonNotebookSource", fullfile(here, 'notebook', 'MachineLearningExample.py'), ...
        "PythonNotebookPath", wsBase + "MATLAB-Classifier-Example" ...
        );
end