% Driver_TrainModel.m
%
% This script shows a full MATLAB desktop workflow to read data from a .csv
% file, train a machine learning model (with the Classification Learner
% App), then use that trained model to predict on new data.

% Copyright 2021-2026 The MathWorks, Inc.

%% STEP 0 - DO THIS FIRST!

% Begin by copying the example to a temporary working directory:
workDir = fullfile(tempdir, "MachineLearning");
copyfile(databricksRoot("examples", "MachineLearning"), workDir)
cd(workDir)

% In order to run this example, you need to download the source data
% "diabetes_data.csv" and place it in the folder called "data".
% https://www.kaggle.com/andrewmvd/early-diabetes-classification

% If you intend to read the data from your Databricks cluster you must
% upload it to /Volumes. For our case, we put it in the following location
% with the databricks.Files upload method

% Must be Customized if using /Volumes based data !! 
% f = databricks.Files();
% FilePath = "/Volumes/main/default/myvolume/Examples/MachineLearning/diabetes_data.csv";
% f.upload(fullfile(".", "data", "diabetes_data.csv"), FilePath)


%% Read data
% Data can be read from the local file system or from Databricks. In this
% example, we read it locally, but code for both options is available.

ReadLocation = "Local"; % Can be Local or Volumes

if strcmpi(ReadLocation, "Local")
    FilePath = fullfile(".", "data", "diabetes_data.csv");
    assert(isfile(FilePath), "File not found: " + FilePath + ". Please download diabetes_data.csv from https://www.kaggle.com/andrewmvd/early-diabetes-classification and place it in the data folder.")
else
    % Set to customized /Volumes path above
end


clusterId = databricks.internal.configurationprofile.ConfigFile.getProfileField("cluster_id");
assert(strlength(clusterId) > 0 , "A cluster Id must be provided or configured in the default profile.");
% e.g. clusterId = "1018-132216-hc5k8ay4";

data = utils.readSampleData(ReadLocation, FilePath, clusterId);

% Take a look at the data to quickly understand what we are dealing with
head(data, 5)


%% Encode the gender variable (for ML work)
% The ML algo expects numeric data, not strings
data.gender = utils.encodeArray(data.gender);


%% Split the data into training and testing sets
rng(1234)
cv = cvpartition(data.class, 'Holdout', 0.3);
trainData = data(cv.training,:);
testData  = data(cv.test,:);


%% Train a NN model
% Note, here we are using the training data to "teach" the model
[trainedClassifier, validationAccuracy] = model.trainClassifier(trainData);
fprintf('\nValidation Accuracy = %0.2f%%\n', validationAccuracy * 100)


% Notes
% This model was trained with the aid of the Classification Learner App.
% The choice of a Neural Network model was arbitrary. You can choose
% whatever model type you need to.

% See this link for more details:
% https://www.mathworks.com/help/releases/R2021b/stats/classification-learner-app.html?s_tid=doc_srchtitle

% The function "trainClassifier.m" (found in the +model folder) was
% auto-generated by the Classification Learner app. The function was saved
% in the "+model" folder for organizational purposes.


%% Predict with the model we just trained (on data it has never seen)
% Note, here we are evaluating the model on the "test data"
[yfit, acc] = model.predictOutcomes(testData, trainedClassifier);
fprintf('\nTest Data Accuracy = %0.2f%%\n', acc)


%% Save the ML model so it can be used later on
save("+model/TrainedModel.mat", "trainedClassifier");

