function varargout = override_feedback(varargin)
    %OVERRIDE_FEEDBACK Overrides an existing feedback assessment with a new assessment. This API
    % logs a new assessment with the `overrides` field set to the provided assessment ID.
    % The original assessment will be marked as invalid, but will otherwise be unchanged.
    % This is useful when you want to correct an assessment generated by an LLM judge,
    % but want to preserve the original assessment for future judge fine-tuning.
    % If you want to mutate an assessment in-place, use :py:func:`update_assessment` instead.
    %
    %   out = mlflow.override_feedback()
    %
    % Returns: 
    %
    %    :py:class:`~mlflow.entities.Assessment`: The created assessment.
    %
    % Input arguments:
    %
    %    trace_id
    %        The ID of the trace.
    %
    %    assessment_id
    %        The ID of the assessment to override.
    %
    %    value
    %        The new value of the assessment.
    %
    %    rationale
    %        The rationale of the new assessment.
    %
    %    source
    %        The source of the new assessment.
    %
    %    metadata
    %        Additional metadata for the new assessment.
    %
    
    % This file has automatically been generated based on
    % MLflow Python SDK version 3.10.1.
    
    % Copyright 2023-2026 MathWorks, Inc.
    
    mlflow.matlab.assertPythonMLflowAvailable()
    args = [];
    i = mlflow.matlab.internal.pythonPositionalSplit(varargin,args);
    [varargout{1:nargout}] = py.mlflow.override_feedback(varargin{1:i},pyargs(varargin{i+1:end}));
