classdef StatementExecution < databricks.statementexecution.BaseClient
    % StatementExecution No description provided
    %
    % StatementExecution Properties:
    %
    %   serverUri           - Base URI to use when calling the API. Allows using a different server
    %                         than specified in the original API spec.
    %   httpOptions         - HTTPOptions used by all requests.
    %   preferredAuthMethod - If operation supports multiple authentication methods, specified which
    %                         method to prefer.
    %   bearerToken         - If Bearer token authentication is used, the token can be supplied 
    %                         here. Note the token is only used if operations are called for which
    %                         the API explicitly specified that Bearer authentication is supported.
    %                         If this has not been specified in the spec but most operations do 
    %                         require Bearer authentication, consider adding the relevant header to
    %                         all requests in the preSend method.
    %   apiKey              - If API key authentication is used, the key can be supplied here. 
    %                         Note the key is only used if operations are called for which
    %                         the API explicitly specified that API key authentication is supported.
    %                         If this has not been specified in the spec but most operations do 
    %                         require API key authentication, consider adding the API key to all
    %                         requests in the preSend method.
    %   httpCredentials     - If Basic or Digest authentication is supported username/password
    %                         credentials can be supplied here as matlab.net.http.Credentials. Note 
    %                         these are only actively used if operations are called for which the 
    %                         API spec has specified they require Basic authentication. If this has
    %                         not been specified in the spec but most operations do require
    %                         Basic authentication, consider setting the Credentials property in the
    %                         httpOptions rather than through httpCredentials.
    %   cookies             - Cookie jar. The cookie jar is shared across all Api classes in the 
    %                         same package. All responses are automatically parsed for Set-Cookie
    %                         headers and cookies are automatically added to the jar. Similarly
    %                         cookies are added to outgoing requests if there are matching cookies 
    %                         in the jar for the given request. Cookies can also be added manually
    %                         by calling the setCookies method on the cookies property. The cookie
    %                         jar is also saved to disk (cookies.mat in the same directory as 
    %                         BaseClient) and reloaded in new MATLAB sessions.
    %
    % StatementExecution Methods:
    %
    %   StatementExecution - Constructor
    %   cancelExecution - Cancel statement execution
    %   executeStatement - Execute a SQL statement
    %   getStatement - Get status, manifest, and result first chunk
    %   getStatementResultChunkN - Get result chunk by index
    %
    % See Also: matlab.net.http.HTTPOptions, matlab.net.http.Credentials, 
    %   CookieJar.setCookies, databricks.statementexecution.BaseClient

    % This file is automatically generated using OpenAPI
    % Specification version: 2.0.0
    % MATLAB Generator for OpenAPI version: 3.0.3
    % (c) 2023-2025 MathWorks Inc.

    % Instruct MATLAB Code Analyzer to ignore unnecessary brackets
    %#ok<*NBRAK2> 

    % Class properties
    properties
    end

    % Class methods
    methods
        function obj = StatementExecution(options)
            % StatementExecution Constructor, creates a StatementExecution instance.
            % When called without inputs, tries to load configuration
            % options from JSON file 'databricks.statementexecution.Client.Settings.json'.
            % If this file is not present, the instance is initialized with 
            % default configuration option.
            % All other properties of the instance can also be overridden 
            % using Name-Value pairs where Name equals the property name.
            % 
            % Examples:
            %
            %   % Create a client with default options and serverUri
            %   % as parsed from OpenAPI spec (if available)
            %   client = databricks.statementexecution.api.StatementExecution();
            %
            %   % Create a client for alternative server/base URI
            %   client = databricks.statementexecution.api.StatementExecution("serverUri","https://example.com:1234/api/");
            %
            %   % Create a client with alternative HTTPOptions and an API key
            %   client = databricks.statementexecution.api.StatementExecution("httpOptions",...
            %       matlab.net.http.HTTPOptions("ConnectTimeout",42),...
            %       "apiKey", "ABC123");

            arguments
                % Configuration specific to the StatementExecution class
                options.profileName string {mustBeTextScalar, mustBeNonzeroLengthText} = databricks.internal.configurationprofile.ConfigFile.getDefaultProfileName
                options.?databricks.statementexecution.BaseClient
            end
            % Get the token and host to configure the default values
            d = databricks.Object;
            d.getAuth("profileName", options.profileName);

            if ~isfield(options, 'bearerToken')
                options.bearerToken = d.Token;
            end
            if ~isfield(options, 'serverUri')
                options.serverUri =  matlab.net.URI(d.Host);
            end

            options = rmfield(options, 'profileName');

            % Call base constructor to override any configured settings
            args = namedargs2cell(options);
            obj@databricks.statementexecution.BaseClient(args{:})
        end

        function [code, result, response] = cancelExecution(obj, statement_id)
            % cancelExecution Cancel statement execution
            % Requests that an executing statement be canceled. Callers must poll for status to see the terminal state. 
            %
            % Required parameters:
            %   statement_id - No description provided, Type: string
            %
            % No optional parameters
            %
            % Responses:
            %   200: Cancel response is empty; receiving response indicates successful receipt.
            %   0: 
            %
            % Returns: 
            %
            % See Also: databricks.statementexecution.models.
            arguments
              obj databricks.statementexecution.api.StatementExecution
              statement_id string
            end

            % Create the request object
            request = matlab.net.http.RequestMessage();
            
            % Verify that operation supports returning JSON
            specAcceptHeaders = [...
                "application/json", ...
            ];
            if ismember("application/json",specAcceptHeaders)
                request.Header(end+1) = matlab.net.http.field.AcceptField('application/json');
            else
                error("databricks:statementexecution:api:cancelExecution:UnsupportedMediaType","Generated OpenAPI Classes only support 'application/json' MediaType.\n" + ...
                    "Operation '%s' does not support this. It may be possible to call this operation by first editing the generated code.","cancelExecution")
            end
            
            % No body input, so no need to check its content type
            
            % No header parameters

            % Configure default httpOptions
            httpOptions = obj.httpOptions;
            % Never convert API response
            httpOptions.ConvertResponse = false;

            % Configure request verb/method
            request.Method = matlab.net.http.RequestMethod('POST');

            % Build the request URI
            if ~isempty(obj.serverUri)
                % If URI specified in object, use that
                uri = obj.serverUri;
            else
                % If no server specified use base path from OpenAPI spec
                uri = matlab.net.URI("https://$DATABRICKS_HOST");
            end
            % Append the operation end-point
            uri.EncodedPath = uri.EncodedPath + "/api/2.0/sql/statements/{statement_id}/cancel";

            % Substitute path parameters
            uri.Path = replace(uri.Path, "{" + "statement_id" + "}", string(statement_id));

            % No query parameters
            
            % No JSON body parameters

            % No form body parameters

            % Configure Authentication
            authNames = [...
                "bearerAuth", ...
            ];  
            [request, httpOptions, uri] = obj.requestAuth(authNames, request, httpOptions, uri);

            % Add cookies if set
            request = obj.applyCookies(request, uri);

            % Call preSend
            [request, httpOptions, uri] = obj.preSend("cancelExecution", request, httpOptions, uri);

            % Perform the request
            [response, ~, history] = send(request, uri, httpOptions);

            % Handle cookies if set
            obj.setCookies(history);

            % Call postSend
            response = obj.postSend("cancelExecution", response, request, uri, httpOptions);

            % Handle response
            code = response.StatusCode;
            switch (code)
                case 200
                    result = response.Body.Data;
                otherwise % Default output as specified in spec
                    result = databricks.statementexecution.models.ServiceError().fromJSON(response.Body.Data);
            end
        
        end % cancelExecution method

        function [code, result, response] = executeStatement(obj, ExecuteStatementRequest)
            % executeStatement Execute a SQL statement
            % Execute a SQL statement, and if flagged as such, await its result for a specified time. 
            %
            % Required parameters:
            %   ExecuteStatementRequest - No description provided, Type: ExecuteStatementRequest
            %       Required properties in the model for this call:
            %       Optional properties in the model for this call:
            %           byte_limit
            %           catalog
            %           disposition
            %           format
            %           on_wait_timeout
            %           schema
            %           statement
            %           wait_timeout
            %           warehouse_id
            %
            % No optional parameters
            %
            % Responses:
            %   200: 
            %   0: 
            %
            % Returns: executeStatement_200_response
            %
            % See Also: databricks.statementexecution.models.executeStatement_200_response
            arguments
              obj databricks.statementexecution.api.StatementExecution
              ExecuteStatementRequest databricks.statementexecution.models.ExecuteStatementRequest
            end

            % Create the request object
            request = matlab.net.http.RequestMessage();
            
            % Verify that operation supports returning JSON
            specAcceptHeaders = [...
                "application/json", ...
            ];
            if ismember("application/json",specAcceptHeaders)
                request.Header(end+1) = matlab.net.http.field.AcceptField('application/json');
            else
                error("databricks:statementexecution:api:executeStatement:UnsupportedMediaType","Generated OpenAPI Classes only support 'application/json' MediaType.\n" + ...
                    "Operation '%s' does not support this. It may be possible to call this operation by first editing the generated code.","executeStatement")
            end
            
            % Verify that operation supports JSON or FORM as input
            specContentTypeHeaders = [...
                "application/json", ...
            ];
            if ismember("application/json",specContentTypeHeaders)
                request.Header(end+1) = matlab.net.http.field.ContentTypeField('application/json');
            elseif ismember("application/x-www-form-urlencoded",specContentTypeHeaders)
                request.Header(end+1) = matlab.net.http.field.ContentTypeField('application/x-www-form-urlencoded');
            else
                error("databricks:statementexecution:api:executeStatement:UnsupportedMediaType","Generated OpenAPI Classes only support 'application/json' and 'application/x-www-form-urlencoded' MediaTypes.\n" + ...
                    "Operation '%s' does not support this. It may be possible to call this operation by first editing the generated code.","executeStatement")
            end
            
            % No header parameters

            % Configure default httpOptions
            httpOptions = obj.httpOptions;
            % Never convert API response
            httpOptions.ConvertResponse = false;

            % Configure request verb/method
            request.Method = matlab.net.http.RequestMethod('POST');

            % Build the request URI
            if ~isempty(obj.serverUri)
                % If URI specified in object, use that
                uri = obj.serverUri;
            else
                % If no server specified use base path from OpenAPI spec
                uri = matlab.net.URI("https://$DATABRICKS_HOST");
            end
            % Append the operation end-point
            uri.EncodedPath = uri.EncodedPath + "/api/2.0/sql/statements/";

            % No path parameters

            % No query parameters
            
            % Set JSON Body
            requiredProperties = [...
            ];
            optionalProperties = [...
                "byte_limit",...
                "catalog",...
                "disposition",...
                "format",...
                "on_wait_timeout",...
                "schema",...
                "statement",...
                "wait_timeout",...
                "warehouse_id",...
            ];
            request.Body(1).Payload = ExecuteStatementRequest.getPayload(requiredProperties,optionalProperties);

            % No form body parameters

            % Configure Authentication
            authNames = [...
                "bearerAuth", ...
            ];  
            [request, httpOptions, uri] = obj.requestAuth(authNames, request, httpOptions, uri);

            % Add cookies if set
            request = obj.applyCookies(request, uri);

            % Call preSend
            [request, httpOptions, uri] = obj.preSend("executeStatement", request, httpOptions, uri);

            % Perform the request
            [response, ~, history] = send(request, uri, httpOptions);

            % Handle cookies if set
            obj.setCookies(history);

            % Call postSend
            response = obj.postSend("executeStatement", response, request, uri, httpOptions);

            % Handle response
            code = response.StatusCode;
            switch (code)
                case 200
                    result = databricks.statementexecution.models.executeStatement_200_response().fromJSON(response.Body.Data);
                otherwise % Default output as specified in spec
                    result = databricks.statementexecution.models.ServiceError().fromJSON(response.Body.Data);
            end
        
        end % executeStatement method

        function [code, result, response] = getStatement(obj, statement_id)
            % getStatement Get status, manifest, and result first chunk
            % This request can be used to poll for the statement''s status. When the `status.state` field is `SUCCEEDED` it will also return the result manifest and the first chunk of the result data. When the statement is in the terminal states `CANCELED`, `CLOSED` or `FAILED`, it returns HTTP 200 with the state set. After at least 12 hours in terminal state, the statement is removed from the warehouse and further calls will receive an HTTP 404 response.  **NOTE** This call currently may take up to 5 seconds to get the latest status and result. 
            %
            % Required parameters:
            %   statement_id - No description provided, Type: string
            %
            % No optional parameters
            %
            % Responses:
            %   200: 
            %   0: 
            %
            % Returns: executeStatement_200_response
            %
            % See Also: databricks.statementexecution.models.executeStatement_200_response
            arguments
              obj databricks.statementexecution.api.StatementExecution
              statement_id string
            end

            % Create the request object
            request = matlab.net.http.RequestMessage();
            
            % Verify that operation supports returning JSON
            specAcceptHeaders = [...
                "application/json", ...
            ];
            if ismember("application/json",specAcceptHeaders)
                request.Header(end+1) = matlab.net.http.field.AcceptField('application/json');
            else
                error("databricks:statementexecution:api:getStatement:UnsupportedMediaType","Generated OpenAPI Classes only support 'application/json' MediaType.\n" + ...
                    "Operation '%s' does not support this. It may be possible to call this operation by first editing the generated code.","getStatement")
            end
            
            % No body input, so no need to check its content type
            
            % No header parameters

            % Configure default httpOptions
            httpOptions = obj.httpOptions;
            % Never convert API response
            httpOptions.ConvertResponse = false;

            % Configure request verb/method
            request.Method = matlab.net.http.RequestMethod('GET');

            % Build the request URI
            if ~isempty(obj.serverUri)
                % If URI specified in object, use that
                uri = obj.serverUri;
            else
                % If no server specified use base path from OpenAPI spec
                uri = matlab.net.URI("https://$DATABRICKS_HOST");
            end
            % Append the operation end-point
            uri.EncodedPath = uri.EncodedPath + "/api/2.0/sql/statements/{statement_id}";

            % Substitute path parameters
            uri.Path = replace(uri.Path, "{" + "statement_id" + "}", string(statement_id));

            % No query parameters
            
            % No JSON body parameters

            % No form body parameters

            % Configure Authentication
            authNames = [...
                "bearerAuth", ...
            ];  
            [request, httpOptions, uri] = obj.requestAuth(authNames, request, httpOptions, uri);

            % Add cookies if set
            request = obj.applyCookies(request, uri);

            % Call preSend
            [request, httpOptions, uri] = obj.preSend("getStatement", request, httpOptions, uri);

            % Perform the request
            [response, ~, history] = send(request, uri, httpOptions);

            % Handle cookies if set
            obj.setCookies(history);

            % Call postSend
            response = obj.postSend("getStatement", response, request, uri, httpOptions);

            % Handle response
            code = response.StatusCode;
            switch (code)
                case 200
                    result = databricks.statementexecution.models.executeStatement_200_response().fromJSON(response.Body.Data);
                otherwise % Default output as specified in spec
                    result = databricks.statementexecution.models.ServiceError().fromJSON(response.Body.Data);
            end
        
        end % getStatement method

        function [code, result, response] = getStatementResultChunkN(obj, statement_id, chunk_index)
            % getStatementResultChunkN Get result chunk by index
            % After the statement execution has `SUCCEEDED`, the result data can be fetched by chunks. Whereas the first chuck with `chunk_index=0` is typically fetched through a `get status` request, subsequent chunks can be fetched using a `get result` request. The response structure is identical to the nested `result` element described in the `get status` request, and similarly includes the `next_chunk_index` and `next_chunk_internal_link` fields for simple iteration through the result set. 
            %
            % Required parameters:
            %   statement_id - No description provided, Type: string
            %   chunk_index - No description provided, Type: int32, Format: int32
            %
            % No optional parameters
            %
            % Responses:
            %   200: Successful return; depending on `disposition` returns chunks of data either inline, or as links.
            %   0: 
            %
            % Returns: ResultData
            %
            % See Also: databricks.statementexecution.models.ResultData
            arguments
              obj databricks.statementexecution.api.StatementExecution
              statement_id string
              chunk_index int32
            end

            % Create the request object
            request = matlab.net.http.RequestMessage();
            
            % Verify that operation supports returning JSON
            specAcceptHeaders = [...
                "application/json", ...
            ];
            if ismember("application/json",specAcceptHeaders)
                request.Header(end+1) = matlab.net.http.field.AcceptField('application/json');
            else
                error("databricks:statementexecution:api:getStatementResultChunkN:UnsupportedMediaType","Generated OpenAPI Classes only support 'application/json' MediaType.\n" + ...
                    "Operation '%s' does not support this. It may be possible to call this operation by first editing the generated code.","getStatementResultChunkN")
            end
            
            % No body input, so no need to check its content type
            
            % No header parameters

            % Configure default httpOptions
            httpOptions = obj.httpOptions;
            % Never convert API response
            httpOptions.ConvertResponse = false;

            % Configure request verb/method
            request.Method = matlab.net.http.RequestMethod('GET');

            % Build the request URI
            if ~isempty(obj.serverUri)
                % If URI specified in object, use that
                uri = obj.serverUri;
            else
                % If no server specified use base path from OpenAPI spec
                uri = matlab.net.URI("https://$DATABRICKS_HOST");
            end
            % Append the operation end-point
            uri.EncodedPath = uri.EncodedPath + "/api/2.0/sql/statements/{statement_id}/result/chunks/{chunk_index}";

            % Substitute path parameters
            uri.Path = replace(uri.Path, "{" + "statement_id" + "}", string(statement_id));
            uri.Path = replace(uri.Path, "{" + "chunk_index" + "}", string(chunk_index));

            % No query parameters
            
            % No JSON body parameters

            % No form body parameters

            % Configure Authentication
            authNames = [...
                "bearerAuth", ...
            ];  
            [request, httpOptions, uri] = obj.requestAuth(authNames, request, httpOptions, uri);

            % Add cookies if set
            request = obj.applyCookies(request, uri);

            % Call preSend
            [request, httpOptions, uri] = obj.preSend("getStatementResultChunkN", request, httpOptions, uri);

            % Perform the request
            [response, ~, history] = send(request, uri, httpOptions);

            % Handle cookies if set
            obj.setCookies(history);

            % Call postSend
            response = obj.postSend("getStatementResultChunkN", response, request, uri, httpOptions);

            % Handle response
            code = response.StatusCode;
            switch (code)
                case 200
                    result = databricks.statementexecution.models.ResultData().fromJSON(response.Body.Data);
                otherwise % Default output as specified in spec
                    result = databricks.statementexecution.models.ServiceError().fromJSON(response.Body.Data);
            end
        
        end % getStatementResultChunkN method

    end %methods
end %class


