function schemaFileName = generateFunctionSchema(funcName, IN, OUT, options)
    % generateFunctionSchema Generate schema file for a function
    %
    % This function creates a schema file that provides the SparkBuilder
    % with additional information when compiling functions that should run
    % on Spark clusters.
    %
    % Required arguments:
    %       funcName : The name of the function or the file
    %             IN : A cell array of arguments for the function
    %
    % Optional argument:
    %            OUT : A cell array of return values for the function
    %
    % Optional named argument:
    %        verbose : Logical flag to enable verbose output, default: false
    %
    %
    % By default automatically create a .schema file in the same location as the
    % function, but with the ending ".schema" instead of ".m".
    %
    % The function returns a string with the path of schema file.
    % This is generally not required.
    %
    % Examples:
    %   % Importing the function, to make examples shorter
    %   import compiler.build.spark.schema.mathworks.generateFunctionSchema
    %
    %   % A function that takes 3 scalar double values, and returns two
    %   % double scalars:
    %   generateFunctionSchema('simplecalc', {3, 4, 5}, {1, 2});
    %
    %   % The same schema can be generated by simply omitting the output
    %   % values. In this case, the function will simply call the actual
    %   % function with the input values provided, and use the results of this
    %   % as the OUT argument.
    %   generateFunctionSchema('simplecalc', {3, 4, 5});
    %
    %   % A function that takes a table and a scalar, and returns another table
    %   generateFunctionSchema('gaussianFilter', {T_in, 4});

    % Copyright 2024-2026 The MathWorks, Inc.

    arguments (Input)
        funcName {mustBeA(funcName, ["function_handle", "string", "char"])}
        IN (1,:) cell
        OUT cell = {}
        options.verbose (1,1) logical = false
    end
    arguments (Output)
        schemaFileName string {mustBeFile}
    end

    if ischar(funcName)
        funcName = string(funcName);
    end

    FIS = compiler.build.spark.internal.getFcnFileName(funcName);
    
    schemaFileName = compiler.build.spark.internal.getSchemaName(FIS.FullFileName);
 
    nIn = nargin(FIS.FuncHandle);
    nOut = nargout(FIS.FuncHandle);
    
    % If no OUT argument was given, try generating this
    if isempty(OUT)
        try
            path_= FIS.FullPath;
            if ~isempty(path_) && strlength(path_) > 0
                if string(pwd) ~= path_
                    old = cd(path_);
                    goBack = onCleanup(@() cd(old));
                end
            end
            if nOut < 0
                error("SPARK_API:no_varargout_for_schema", ...
                    "A function, for which a schema is generated, cannot have varargout as output");
            end
            OUT = cell(1,nOut);
            [OUT{1:nOut}] = FIS.FuncHandle(IN{:});
        catch EX
            if strcmp(EX.identifier, 'SPARK_API:no_varargout_for_schema')
                rethrow(EX);
            else
                error("SPARK_API:bad_function_name_schema", ...
                    "The function name provided, %s, could not be evaluated properly.\n" + ...
                    "Verify that the function can be called from the command line.", funcName);
            end
        end
    end

    [inArgNames, outArgNames] = compiler.build.spark.internal.getArgNames(FIS.FullFileName);
    if isempty(inArgNames) && nIn > 0
        inArgNames = "in_" + (1:nIn);
    end
    if isempty(outArgNames) && nOut > 0
        outArgNames = "out_" + (1:nOut);
    end
    
    CT = getSparkSchema(FIS.FuncName, IN, OUT, inArgNames, outArgNames);

    CT.checkTypeCompliance();

    fh = fopen(schemaFileName, "w");
    if fh < 0
        error("Could not write to file: '%s'\n", schemaFileName);
    end
    fprintf(fh, '%s\n', CT.json(pretty=true));
    fclose(fh);

    if options.verbose
        fprintf("Generated function schema: %s\n", schemaFileName);
    end
end

function CT = getSparkSchema(funcName, IN, OUT, inArgNames, outArgNames)
    CT = compiler.build.spark.schema.mathworks.CompilerType(funcName);
    for k=1:numel(IN)
        name = inArgNames{k};
        schema = compiler.build.spark.schema.DataType.createSchema(IN{k});
        CT.addInput(name, schema, istable(IN{k}));
    end
    for k=1:numel(OUT)
        name = outArgNames{k};
        schema = compiler.build.spark.schema.DataType.createSchema(OUT{k});
        CT.addOutput(name, schema, istable(OUT{k}));
    end
end