classdef CredentialType < JSONEnum
    % CredentialType The type of credential enumeration.
    %
    % Enumeration Values:
    %   UNKNOWN_CREDENTIAL_TYPE
    %   USERNAME_PASSWORD
    %   OAUTH_U2M
    %   OAUTH_M2M
    %   OAUTH_REFRESH_TOKEN
    %   OAUTH_ACCESS_TOKEN
    %   OAUTH_RESOURCE_OWNER_PASSWORD
    %   SERVICE_CREDENTIAL
    %   BEARER_TOKEN
    %   OIDC_TOKEN
    %   PEM_PRIVATE_KEY
    %   OAUTH_U2M_MAPPING
    %   ANY_STATIC_CREDENTIAL
    %   OAUTH_MTLS
    %   SSWS_TOKEN
    %   EDGEGRID_AKAMAI

    % Copyright 2026 The MathWorks, Inc.

    enumeration
        UNKNOWN_CREDENTIAL_TYPE ("UNKNOWN_CREDENTIAL_TYPE")
        USERNAME_PASSWORD ("USERNAME_PASSWORD")
        OAUTH_U2M ("OAUTH_U2M")
        OAUTH_M2M ("OAUTH_M2M")
        OAUTH_REFRESH_TOKEN ("OAUTH_REFRESH_TOKEN")
        OAUTH_ACCESS_TOKEN ("OAUTH_ACCESS_TOKEN")
        OAUTH_RESOURCE_OWNER_PASSWORD ("OAUTH_RESOURCE_OWNER_PASSWORD")
        SERVICE_CREDENTIAL ("SERVICE_CREDENTIAL")
        BEARER_TOKEN ("BEARER_TOKEN")
        OIDC_TOKEN ("OIDC_TOKEN")
        PEM_PRIVATE_KEY ("PEM_PRIVATE_KEY")
        OAUTH_U2M_MAPPING ("OAUTH_U2M_MAPPING")
        ANY_STATIC_CREDENTIAL ("ANY_STATIC_CREDENTIAL")
        OAUTH_MTLS ("OAUTH_MTLS")
        SSWS_TOKEN ("SSWS_TOKEN")
        EDGEGRID_AKAMAI ("EDGEGRID_AKAMAI")
    end
end
