classdef ColumnInfoType_nameEnum < databricks.statementexecution.JSONEnum
% ColumnInfoType_nameEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2.0.0
    % MATLAB Generator for OpenAPI version: 3.0.3
    % (c) 2023-2025 MathWorks Inc.

    properties  (Constant)
        baseType = ""
    end

    enumeration 
        BOOLEAN ("BOOLEAN")
        BYTE ("BYTE")
        SHORT ("SHORT")
        INT ("INT")
        LONG ("LONG")
        FLOAT ("FLOAT")
        DOUBLE ("DOUBLE")
        DATE ("DATE")
        TIMESTAMP ("TIMESTAMP")
        STRING ("STRING")
        BINARY ("BINARY")
        DECIMAL ("DECIMAL")
        INTERVAL ("INTERVAL")
        ARRAY ("ARRAY")
        STRUCT ("STRUCT")
        MAP ("MAP")
        CHAR ("CHAR")
        NULL ("NULL")
        USER_DEFINED_TYPE ("USER_DEFINED_TYPE")
    end

end %class

