classdef ColumnInfo < databricks.statementexecution.JSONMapper
% ColumnInfo No description provided
% 
% ColumnInfo Properties:
%   name - Name of Column. - type: string
%   position - Ordinal position of column (starting at position 0). - type: int32
%   type_interval_type - Format of interval type. - type: string
%   type_name - Name of type (INT, STRUCT, MAP, and so on) - type: string
%   type_precision - Digits of precision. - type: int32
%   type_scale - Digits to right of decimal. - type: int32
%   type_text - Full data type spec, SQL/catalogString text. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % name - Name of Column. - type: string
        name string { databricks.statementexecution.JSONMapper.fieldName(name,"name")}
        % position - Ordinal position of column (starting at position 0). - type: int32
        position int32 { databricks.statementexecution.JSONMapper.fieldName(position,"position")}
        % type_interval_type - Format of interval type. - type: string
        type_interval_type string { databricks.statementexecution.JSONMapper.fieldName(type_interval_type,"type_interval_type")}
        % type_name - Name of type (INT, STRUCT, MAP, and so on) - type: string
        type_name databricks.statementexecution.models.ColumnInfoType_nameEnum { databricks.statementexecution.JSONMapper.fieldName(type_name,"type_name")}
        % type_precision - Digits of precision. - type: int32
        type_precision int32 { databricks.statementexecution.JSONMapper.fieldName(type_precision,"type_precision")}
        % type_scale - Digits to right of decimal. - type: int32
        type_scale int32 { databricks.statementexecution.JSONMapper.fieldName(type_scale,"type_scale")}
        % type_text - Full data type spec, SQL/catalogString text. - type: string
        type_text string { databricks.statementexecution.JSONMapper.fieldName(type_text,"type_text")}
    end

    % Class methods
    methods
        % Constructor
        function obj = ColumnInfo(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ColumnInfo
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

