classdef executeStatement_200_response < databricks.statementexecution.JSONMapper
% executeStatement_200_response No description provided
% 
% executeStatement_200_response Properties:
%   manifest - type: ResultManifest
%   result - type: ResultData
%   statement_id - Statement ID is returned upon successfully submitting a SQL statement, and is a required reference for all subsequent calls.  - type: string
%   status - type: StatementStatus

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % manifest - type: ResultManifest
        manifest databricks.statementexecution.models.ResultManifest { databricks.statementexecution.JSONMapper.fieldName(manifest,"manifest")}
        % result - type: ResultData
        result databricks.statementexecution.models.ResultData { databricks.statementexecution.JSONMapper.fieldName(result,"result")}
        % statement_id - Statement ID is returned upon successfully submitting a SQL statement, and is a required reference for all subsequent calls.  - type: string
        statement_id string { databricks.statementexecution.JSONMapper.fieldName(statement_id,"statement_id")}
        % status - type: StatementStatus
        status databricks.statementexecution.models.StatementStatus { databricks.statementexecution.JSONMapper.fieldName(status,"status")}
    end

    % Class methods
    methods
        % Constructor
        function obj = executeStatement_200_response(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.executeStatement_200_response
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

