classdef ExecuteStatementRequest < databricks.statementexecution.JSONMapper
% ExecuteStatementRequest No description provided
% 
% ExecuteStatementRequest Properties:
%   row_limit - Applies the given row limit to the statement's result set, but unlike the LIMIT clause in SQL, it also sets the truncated field in the response to indicate whether the result was trimmed due to the limit or not. - type: int64
%   byte_limit - Applies the given byte limit to the statement''s result size. Byte counts are based on internal representations and may not match measurable sizes in the requested `format`.  - type: int64
%   catalog - Sets default catalog for statement execution, similar to [`USE CATALOG`](https://docs.microsoft.com/azure/databricks/sql/language-manual/sql-ref-syntax-ddl-use-catalog.html) in SQL.  - type: string
%   disposition - type: Disposition
%   format - type: Format
%   on_wait_timeout - type: TimeoutAction
%   schema - Sets default schema for statement execution, similar to [`USE SCHEMA`](https://docs.microsoft.com/azure/databricks/sql/language-manual/sql-ref-syntax-ddl-use-schema.html) in SQL.  - type: string
%   statement - SQL statement to execute - type: string
%   wait_timeout - The time in seconds the API service will wait for the statement''s result set as `Ns`, where `N` can be set to 0 or to a value between 5 and 50. When set to ''0s'' the statement will execute in asynchronous mode.\"  - type: string
%   warehouse_id - Warehouse upon which to execute a statement. See also [What are SQL warehouses?](https://docs.microsoft.com/azure/databricks/sql/admin/warehouse-type.html)  - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % row_limit - Applies the given row limit to the statement's result set, but unlike the LIMIT clause in SQL, it also sets the truncated field in the response to indicate whether the result was trimmed due to the limit or not. - type: int64
        row_limit int64 { databricks.statementexecution.JSONMapper.fieldName(row_limit,"row_limit") }
        % byte_limit - Applies the given byte limit to the statement''s result size. Byte counts are based on internal representations and may not match measurable sizes in the requested `format`.  - type: int64
        byte_limit int64 { databricks.statementexecution.JSONMapper.fieldName(byte_limit,"byte_limit")}
        % catalog - Sets default catalog for statement execution, similar to [`USE CATALOG`](https://docs.microsoft.com/azure/databricks/sql/language-manual/sql-ref-syntax-ddl-use-catalog.html) in SQL.  - type: string
        catalog string { databricks.statementexecution.JSONMapper.fieldName(catalog,"catalog")}
        % disposition - type: Disposition
        disposition databricks.statementexecution.models.Disposition { databricks.statementexecution.JSONMapper.fieldName(disposition,"disposition")}
        % format - type: Format
        format databricks.statementexecution.models.Format { databricks.statementexecution.JSONMapper.fieldName(format,"format")}
        % on_wait_timeout - type: TimeoutAction
        on_wait_timeout databricks.statementexecution.models.TimeoutAction { databricks.statementexecution.JSONMapper.fieldName(on_wait_timeout,"on_wait_timeout")}
        % schema - Sets default schema for statement execution, similar to [`USE SCHEMA`](https://docs.microsoft.com/azure/databricks/sql/language-manual/sql-ref-syntax-ddl-use-schema.html) in SQL.  - type: string
        schema string { databricks.statementexecution.JSONMapper.fieldName(schema,"schema")}
        % statement - SQL statement to execute - type: string
        statement string { databricks.statementexecution.JSONMapper.fieldName(statement,"statement")}
        % wait_timeout - The time in seconds the API service will wait for the statement''s result set as `Ns`, where `N` can be set to 0 or to a value between 5 and 50. When set to ''0s'' the statement will execute in asynchronous mode.\"  - type: string
        wait_timeout string { databricks.statementexecution.JSONMapper.fieldName(wait_timeout,"wait_timeout")}
        % warehouse_id - Warehouse upon which to execute a statement. See also [What are SQL warehouses?](https://docs.microsoft.com/azure/databricks/sql/admin/warehouse-type.html)  - type: string
        warehouse_id string { databricks.statementexecution.JSONMapper.fieldName(warehouse_id,"warehouse_id")}
        % TODO parameters
    end

    % Class methods
    methods
        % Constructor
        function obj = ExecuteStatementRequest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ExecuteStatementRequest
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

