classdef ExternalLink < databricks.statementexecution.JSONMapper
% ExternalLink No description provided
% 
% ExternalLink Properties:
%   byte_count - Number of bytes in the result chunk. - type: int64
%   chunk_index - Position within the sequence of result set chunks. - type: int32
%   expiration - Indicates date-time that the given external link will expire and become invalid, after which point a new `external_link` must be requested.  - type: datetime
%   external_link - Pre-signed URL pointing to a chunk of result data, hosted by an external service, with a short expiration time (< 1 hour).  - type: string
%   next_chunk_index - When fetching, gives `chunk_index` for the _next_ chunk; if absent, indicates there are no more chunks. - type: int32
%   next_chunk_internal_link - When fetching, gives `internal_link` for the _next_ chunk; if absent, indicates there are no more chunks. - type: string
%   row_count - Number of rows within the result chunk. - type: int64
%   row_offset - Starting row offset within the result set. - type: int64

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % byte_count - Number of bytes in the result chunk. - type: int64
        byte_count int64 { databricks.statementexecution.JSONMapper.fieldName(byte_count,"byte_count")}
        % chunk_index - Position within the sequence of result set chunks. - type: int32
        chunk_index int32 { databricks.statementexecution.JSONMapper.fieldName(chunk_index,"chunk_index")}
        % expiration - Indicates date-time that the given external link will expire and become invalid, after which point a new `external_link` must be requested.  - type: datetime
        expiration datetime { databricks.statementexecution.JSONMapper.stringDatetime(expiration,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), databricks.statementexecution.JSONMapper.fieldName(expiration,"expiration")}
        % external_link - Pre-signed URL pointing to a chunk of result data, hosted by an external service, with a short expiration time (< 1 hour).  - type: string
        external_link string { databricks.statementexecution.JSONMapper.fieldName(external_link,"external_link")}
        % next_chunk_index - When fetching, gives `chunk_index` for the _next_ chunk; if absent, indicates there are no more chunks. - type: int32
        next_chunk_index int32 { databricks.statementexecution.JSONMapper.fieldName(next_chunk_index,"next_chunk_index")}
        % next_chunk_internal_link - When fetching, gives `internal_link` for the _next_ chunk; if absent, indicates there are no more chunks. - type: string
        next_chunk_internal_link string { databricks.statementexecution.JSONMapper.fieldName(next_chunk_internal_link,"next_chunk_internal_link")}
        % row_count - Number of rows within the result chunk. - type: int64
        row_count int64 { databricks.statementexecution.JSONMapper.fieldName(row_count,"row_count")}
        % row_offset - Starting row offset within the result set. - type: int64
        row_offset int64 { databricks.statementexecution.JSONMapper.fieldName(row_offset,"row_offset")}
    end

    % Class methods
    methods
        % Constructor
        function obj = ExternalLink(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ExternalLink
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

