classdef ResultManifest < databricks.statementexecution.JSONMapper
% ResultManifest The result manifest provides schema and metadata for the result set.
% 
% ResultManifest Properties:
%   chunks - Array of result set chunk metadata. - type: array of ChunkInfo
%   format - type: Format
%   schema - type: ResultSchema
%   total_byte_count - Total number of bytes in the result set. - type: int64
%   total_chunk_count - Total number of chunks that the result set has been divided into. - type: int32
%   total_row_count - Total number of rows in the result set. - type: int64

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % chunks - Array of result set chunk metadata. - type: array of ChunkInfo
        chunks databricks.statementexecution.models.ChunkInfo { databricks.statementexecution.JSONMapper.fieldName(chunks,"chunks"), databricks.statementexecution.JSONMapper.JSONArray}
        % format - type: Format
        format databricks.statementexecution.models.Format { databricks.statementexecution.JSONMapper.fieldName(format,"format")}
        % schema - type: ResultSchema
        schema databricks.statementexecution.models.ResultSchema { databricks.statementexecution.JSONMapper.fieldName(schema,"schema")}
        % total_byte_count - Total number of bytes in the result set. - type: int64
        total_byte_count int64 { databricks.statementexecution.JSONMapper.fieldName(total_byte_count,"total_byte_count")}
        % total_chunk_count - Total number of chunks that the result set has been divided into. - type: int32
        total_chunk_count int32 { databricks.statementexecution.JSONMapper.fieldName(total_chunk_count,"total_chunk_count")}
        % total_row_count - Total number of rows in the result set. - type: int64
        total_row_count int64 { databricks.statementexecution.JSONMapper.fieldName(total_row_count,"total_row_count")}
        % Indicates whether the result is truncated due to row_limit or byte_limit. - type: logical
        truncated logical { databricks.statementexecution.JSONMapper.fieldName(truncated,"truncated") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ResultManifest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ResultManifest
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

