classdef ResultSchema < databricks.statementexecution.JSONMapper
% ResultSchema Schema is an ordered list of column descriptions.
% 
% ResultSchema Properties:
%   column_count - type: int32
%   columns - type: array of ColumnInfo

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % column_count - type: int32
        column_count int32 { databricks.statementexecution.JSONMapper.fieldName(column_count,"column_count")}
        % columns - type: array of ColumnInfo
        columns databricks.statementexecution.models.ColumnInfo { databricks.statementexecution.JSONMapper.fieldName(columns,"columns"), databricks.statementexecution.JSONMapper.JSONArray}
    end

    % Class methods
    methods
        % Constructor
        function obj = ResultSchema(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ResultSchema
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

