classdef ResultData < databricks.statementexecution.JSONMapper
% ResultData Result data chunks are delivered in either the `chunk` field when using `INLINE` disposition, or in the `external_link` field when using `EXTERNAL_LINKS` disposition. Exactly one of these will be set. 
% 
% ResultData Properties:
%   byte_count - Number of bytes in the result chunk. - type: int64
%   chunk_index - Position within the sequence of result set chunks. - type: int32
%   data_array - `JSON_ARRAY` format is an array of arrays of values, where each non-null value is formatted as a string. Null values are encoded as JSON `null`.  - type: array of array
%   external_links - type: array of ExternalLink
%   next_chunk_index - When fetching, gives `chunk_index` for the _next_ chunk; if absent, indicates there are no more chunks. - type: int32
%   next_chunk_internal_link - When fetching, gives `internal_link` for the _next_ chunk; if absent, indicates there are no more chunks. - type: string
%   row_count - Number of rows within the result chunk. - type: int64
%   row_offset - Starting row offset within the result set. - type: int64

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % byte_count - Number of bytes in the result chunk. - type: int64
        byte_count int64 { databricks.statementexecution.JSONMapper.fieldName(byte_count,"byte_count")}
        % chunk_index - Position within the sequence of result set chunks. - type: int32
        chunk_index int32 { databricks.statementexecution.JSONMapper.fieldName(chunk_index,"chunk_index")}
        % data_array - `JSON_ARRAY` format is an array of arrays of values, where each non-null value is formatted as a string. Null values are encoded as JSON `null`.  - type: array of array
        data_array { databricks.statementexecution.JSONMapper.fieldName(data_array,"data_array"), databricks.statementexecution.JSONMapper.doNotDecode, databricks.statementexecution.JSONMapper.JSONArray}
        % data_array { databricks.statementexecution.JSONMapper.fieldName(data_array,"data_array"), databricks.statementexecution.JSONMapper.JSONArray}
        % external_links - type: array of ExternalLink
        external_links databricks.statementexecution.models.ExternalLink { databricks.statementexecution.JSONMapper.fieldName(external_links,"external_links"), databricks.statementexecution.JSONMapper.JSONArray}
        % next_chunk_index - When fetching, gives `chunk_index` for the _next_ chunk; if absent, indicates there are no more chunks. - type: int32
        next_chunk_index int32 { databricks.statementexecution.JSONMapper.fieldName(next_chunk_index,"next_chunk_index")}
        % next_chunk_internal_link - When fetching, gives `internal_link` for the _next_ chunk; if absent, indicates there are no more chunks. - type: string
        next_chunk_internal_link string { databricks.statementexecution.JSONMapper.fieldName(next_chunk_internal_link,"next_chunk_internal_link")}
        % row_count - Number of rows within the result chunk. - type: int64
        row_count int64 { databricks.statementexecution.JSONMapper.fieldName(row_count,"row_count")}
        % row_offset - Starting row offset within the result set. - type: int64
        row_offset int64 { databricks.statementexecution.JSONMapper.fieldName(row_offset,"row_offset")}
    end

    % Class methods
    methods
        % Constructor
        function obj = ResultData(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ResultData
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

