classdef ServiceError < databricks.statementexecution.JSONMapper
% ServiceError No description provided
% 
% ServiceError Properties:
%   error_code - type: ServiceErrorCode
%   message - Brief summary of error condition. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % error_code - type: ServiceErrorCode
        error_code databricks.statementexecution.models.ServiceErrorCode { databricks.statementexecution.JSONMapper.fieldName(error_code,"error_code")}
        % message - Brief summary of error condition. - type: string
        message string { databricks.statementexecution.JSONMapper.fieldName(message,"message")}
    end

    % Class methods
    methods
        % Constructor
        function obj = ServiceError(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.ServiceError
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

