classdef ServiceErrorCode < databricks.statementexecution.JSONEnum
% ServiceErrorCode No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2.0.0
    % MATLAB Generator for OpenAPI version: 3.0.3
    % (c) 2023-2025 MathWorks Inc.

    properties  (Constant)
        baseType = "string"
    end

    enumeration 
        UNKNOWN ("UNKNOWN")
        INTERNAL_ERROR ("INTERNAL_ERROR")
        TEMPORARILY_UNAVAILABLE ("TEMPORARILY_UNAVAILABLE")
        IO_ERROR ("IO_ERROR")
        BAD_REQUEST ("BAD_REQUEST")
        SERVICE_UNDER_MAINTENANCE ("SERVICE_UNDER_MAINTENANCE")
        WORKSPACE_TEMPORARILY_UNAVAILABLE ("WORKSPACE_TEMPORARILY_UNAVAILABLE")
        DEADLINE_EXCEEDED ("DEADLINE_EXCEEDED")
        CANCELLED ("CANCELLED")
        RESOURCE_EXHAUSTED ("RESOURCE_EXHAUSTED")
        ABORTED ("ABORTED")
        NOT_FOUND ("NOT_FOUND")
        ALREADY_EXISTS ("ALREADY_EXISTS")
        UNAUTHENTICATED ("UNAUTHENTICATED")
    end

end %class

