classdef StatementStatus < databricks.statementexecution.JSONMapper
% StatementStatus Status response includes execution state and if relevant, error information.
% 
% StatementStatus Properties:
%   error - type: ServiceError
%   state - type: StatementState

% This file is automatically generated using OpenAPI
% Specification version: 2.0.0
% MATLAB Generator for OpenAPI version: 3.0.3
% (c) 2023-2025 MathWorks Inc.

    % Class properties
    properties
        % error - type: ServiceError
        error databricks.statementexecution.models.ServiceError { databricks.statementexecution.JSONMapper.fieldName(error,"error")}
        % state - type: StatementState
        state databricks.statementexecution.models.StatementState { databricks.statementexecution.JSONMapper.fieldName(state,"state")}
    end

    % Class methods
    methods
        % Constructor
        function obj = StatementStatus(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { databricks.statementexecution.JSONMapper.ConstructorArgument } = []
                inputs.?databricks.statementexecution.models.StatementStatus
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

