classdef StatementState < databricks.statementexecution.JSONEnum
% StatementState Statement execution state: - `PENDING`: waiting for warehouse - `RUNNING`: running - `SUCCEEDED`: execution was successful, result data available for fetch - `FAILED`: execution failed; reason for failure described in accomanying error message - `CANCELED`: user canceled; can come from explicit cancel call, or timeout with `on_wait_timeout=CANCEL` - `CLOSED`: execution successful, and statement closed; result no longer available for fetch 

    % This file is automatically generated using OpenAPI
    % Specification version: 2.0.0
    % MATLAB Generator for OpenAPI version: 3.0.3
    % (c) 2023-2025 MathWorks Inc.

    properties  (Constant)
        baseType = "string"
    end

    enumeration 
        PENDING ("PENDING")
        RUNNING ("RUNNING")
        SUCCEEDED ("SUCCEEDED")
        FAILED ("FAILED")
        CANCELED ("CANCELED")
        CLOSED ("CLOSED")
    end

end %class

