classdef TimeoutAction < databricks.statementexecution.JSONEnum
% TimeoutAction When in synchronous mode with `wait_timeout > 0s` it determines the action taken when the timeout is reached:  `CONTINUE` → the statement execution continues asynchronously and the call returns a statement ID immediately.  `CANCEL` → the statement execution is canceled and the call returns immediately with a `CANCELED` state. 

    % This file is automatically generated using OpenAPI
    % Specification version: 2.0.0
    % MATLAB Generator for OpenAPI version: 3.0.3
    % (c) 2023-2025 MathWorks Inc.

    properties  (Constant)
        baseType = "string"
    end

    enumeration 
        CONTINUE ("CONTINUE")
        CANCEL ("CANCEL")
    end

end %class

